# Generated by Django 4.2.4 on 2023-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_playerteam_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerteam",
            name="user",
        ),
        migrations.AddField(
            model_name="playerteam",
            name="stations",
            field=models.ManyToManyField(blank=True, null=True, to="backend.station"),
        ),
        migrations.AlterField(
            model_name="playerteam",
            name="score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
