# Generated by Django 4.2.4 on 2023-09-18 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_curator_current_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curator",
            name="current_team",
        ),
    ]
