# Generated by Django 4.2.4 on 2023-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_remove_playerteam_user_playerteam_stations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerteam",
            name="stations",
            field=models.ManyToManyField(blank=True, to="backend.station"),
        ),
    ]
