# Generated by Django 4.2.4 on 2023-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_remove_curator_current_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerteam",
            name="current_station",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
