# Generated by Django 4.2.4 on 2023-08-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_playerteam_stations"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="assignment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
