# Generated by Django 4.2.4 on 2023-09-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_station_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="curator",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.station",
            ),
        ),
        migrations.AddField(
            model_name="playerteam",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
