# Generated by Django 4.2.4 on 2023-09-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_playerteam_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerteam",
            name="current_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_station",
                to="backend.station",
            ),
        ),
    ]
