# Generated by Django 4.2.4 on 2023-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_playerteam_current_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerteam",
            name="time2",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
