# Generated by Django 4.2.4 on 2023-09-10 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_playerteam_time2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerteam",
            name="time",
        ),
    ]
