# Generated by Django 4.2.4 on 2023-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_remove_playerteam_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
