# Generated by Django 4.2.4 on 2023-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_alter_station_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerteam",
            name="time2",
        ),
        migrations.AddField(
            model_name="playerteam",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
