# Generated by Django 4.2.4 on 2023-09-10 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_remove_playerteam_time2_playerteam_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerteam",
            old_name="time",
            new_name="start_time",
        ),
    ]
