# Generated by Django 4.2.4 on 2023-09-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_alter_playerteam_options_alter_playerteam_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerteam",
            name="teamname",
        ),
        migrations.AlterField(
            model_name="playerteam",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
