# Generated by Django 4.2.4 on 2023-09-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_remove_playerteam_teamname_alter_playerteam_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerteam",
            options={},
        ),
        migrations.AlterModelManagers(
            name="playerteam",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="email",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="playerteam",
            name="username",
        ),
        migrations.AddField(
            model_name="playerteam",
            name="teamname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="playerteam",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
