# Generated by Django 4.2.4 on 2023-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0019_remove_curator_name_remove_curator_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curator",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
