# Generated by Django 4.2.4 on 2023-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_curator_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerteam",
            name="teamname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
