# Generated by Django 4.2.4 on 2023-09-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_playerteam_teamname"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerTeamStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "playerteam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.playerteam",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.station",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="playerteam",
            name="stations",
            field=models.ManyToManyField(
                blank=True, through="backend.PlayerTeamStation", to="backend.station"
            ),
        ),
    ]
