# Generated by Django 4.2.4 on 2023-09-10 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_playerteamstation_alter_playerteam_stations"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playerteamstation",
            unique_together={("playerteam", "station")},
        ),
    ]
